[package]
name = "asdasd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
http = "0.2.9"
reqwest = "0.11.14"
tokio = {version = "1.26.0", features = ["macros", "rt-multi-thread"]}
